### ISSUE TITLE
Access to member area unavailable

### ISSUE THREAD

**Issue by mwigham** [polifonia-project/web_portal#3]
When clicking on the button 'Member area', the website simply shows the text 'None'. This is in Chrome.

In Firefox I can fill in my Github login and get sent a verification code, after I fill that in then the website again shows 'None'. 

Back in Chrome, if I first search for my draft record and then click on Member Area, then the behaviour is the same as Firefox.

**Comment by mwigham** [comment]
Hi,

Is there a status update on this issue please? As I can't access the member area, I can't approve the datasets I have added, so they are stuck in limbo :(

Thanks!

**Comment by marilenadaquino** [comment]
Hi @mwigham, apologies I didn't see this issue! I should have fixed the problem (my token was expired, so I could not validate your credentials, hence the error). Could you confirm it works now or send a screenshot of the problem if it persists?

Many thanks

ps. you meant this issue to be in [musoW](https://github.com/polifonia-project/registry_app) - the current repo is for yet-another-website.

**Comment by mwigham** [comment]
Sorry for the wrong repo! 
Thanks for looking into this. I now get a 500 error when I try to go to the member area. It seems to think I am logged in, as the button changes to Logout, but the pages don't work further, except for Explore.
![Knipsel](https://user-images.githubusercontent.com/38520885/200301247-24620c6b-606e-4a05-a79c-1143ed97feff.PNG)

**Comment by marilenadaquino** [comment]
You are logged in indeed. Did you try to click top left on the logo? If you do that, do you see the backend?

I tried now to go to that record is in your screenshot and it seems it does not exist. Is it possible?

**Comment by mwigham** [comment]
If I click on 'musow' in the top left corner, then I get the 500 (Oh, this is bad...). I just clicked on a random record, so it's certainly possible it doesn't exist.

**Comment by marilenadaquino** [comment]
I sent you an invitation on github to become a collaborator of the repo. Can you accept and try to logout and login again?

**Comment by marilenadaquino** [comment]
otherwise, can we go through it on discord?

**Comment by mwigham** [comment]
I'm not seeing the invitation I'm afraid. Unfortunately I need to leave now to catch a train. It would be possible to go through it on Discord either tomorrow morning before 10am, or Friday morning, if either time fits for you.

**Comment by marilenadaquino** [comment]
fixed. notes for myself:

 - must refresh the admin token in conf.py if expired
 - added a redirect to the github authorization page if the user token has expired (usually after a week)
 - if the user email is not public a fake email `username+@polifonia.eu` is created
 - the log function gives some problems if the useremail is not public
